@REM  cd.. devi posizionarti su git_desktop
CD c:\CASA\LINGUAGGI\ACCESS\PROGETTI_MDB\MSYS_OGGETTI\MENU\

dir 

@REM  apro la pagina web


start msedge https://www.overleaf.com/project/678766715c38d59052417047


@rem pausa di 20 secondi per consentire il commit

@REM 01)
@REM sospensione per 1 secondo con crononometro 
@REM ---->	timeout /t 2 /nobreak > NUL
@REM ---->
ECHO
ECHO
ECHO  pausa di 2 secondi per consentire il commit
ECHO
@TIMEOUT /T 2 /NOBREAK

